const BlogActionTypes = {
  UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
  UPDATE_HISTORY: 'UPDATE_HISTORY',
  UPDATE_BLOG_COMMENTS: 'UPDATE_BLOG_COMMENTS',
  UPDATE_BLOG_VIEWS: 'UPDATE_BLOG_VIEWS',
  SET_CURRENT_READING: 'SET_CURRENT_READING',
  SET_READERS_FAVORITE: 'SET_READERS_FAVORITE',
};

export default BlogActionTypes;
